version: '3.1'

services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sca'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '8aLZO9zoTX52hd0'
      MYSQL_ROOT_PASSWORD: '8aLZO9zoTX52hd0'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
